services:
  - type: web
    name: colbee-id
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Cross-Origin-Resource-Policy
        value: cross-origin
      - path: /images/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /card-designs/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /icons/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
